// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzxcJ0OCgl5oe-n6S-73lgE1TGMqKcyU',
    appId: '1:404595228914:web:5a5baa60241aac53db106b',
    messagingSenderId: '404595228914',
    projectId: 'dignity-with-care',
    authDomain: 'dignity-with-care.firebaseapp.com',
    storageBucket: 'dignity-with-care.firebasestorage.app',
    measurementId: 'G-FQ18C33WQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQytihTPKoTW2RFrOUfJlV21fiv2TKsp0',
    appId: '1:404595228914:android:7dd8c1dfc5aaa707db106b',
    messagingSenderId: '404595228914',
    projectId: 'dignity-with-care',
    storageBucket: 'dignity-with-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AZkOT1zEm6CwPOc3QrnYcYbO3edRRlI',
    appId: '1:404595228914:ios:123c1dc44b1976cbdb106b',
    messagingSenderId: '404595228914',
    projectId: 'dignity-with-care',
    storageBucket: 'dignity-with-care.firebasestorage.app',
    iosBundleId: 'com.leosgroup.dignitywithcare.dignitywithcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9AZkOT1zEm6CwPOc3QrnYcYbO3edRRlI',
    appId: '1:404595228914:ios:123c1dc44b1976cbdb106b',
    messagingSenderId: '404595228914',
    projectId: 'dignity-with-care',
    storageBucket: 'dignity-with-care.firebasestorage.app',
    iosBundleId: 'com.leosgroup.dignitywithcare.dignitywithcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCzxcJ0OCgl5oe-n6S-73lgE1TGMqKcyU',
    appId: '1:404595228914:web:a0489d49285b106cdb106b',
    messagingSenderId: '404595228914',
    projectId: 'dignity-with-care',
    authDomain: 'dignity-with-care.firebaseapp.com',
    storageBucket: 'dignity-with-care.firebasestorage.app',
    measurementId: 'G-GGPTNLNDC8',
  );

}